"""
Pydantic models and the in-memory menu database for Café Nourish.
All AI recommendations are restricted to items in MENU_ITEMS.
Nutrition values are per 100g of prepared dish (approximate).
"""
from pydantic import BaseModel
from typing import List, Optional


class Nutrition(BaseModel):
    calories: float   # kcal per 100g
    protein: float    # grams per 100g
    fat: float        # grams per 100g
    carbs: float      # grams per 100g


class MenuItem(BaseModel):
    id: str
    name: str
    category: str
    tags: List[str]
    label: str
    price: int
    description: str
    short_desc: str
    ingredients: List[str]
    profile: List[str]
    why_on_menu: str
    allergens: str
    image: str
    nutrition: Nutrition


class RecommendRequest(BaseModel):
    meal_time: Optional[str] = None
    preference: Optional[str] = None
    priority: Optional[str] = None
    budget: int = 250
    free_text: Optional[str] = None


class RecommendResponse(BaseModel):
    type: str
    items: List[MenuItem]
    disclaimer: str = (
        "These suggestions are based on the preferences you provided and are limited "
        "to items on the Café Nourish menu. They are general food-choice suggestions "
        "only and are not medical or dietary advice. For personalised dietary guidance, "
        "consult a qualified professional."
    )


# ─── Menu database ────────────────────────────────────────────────────────────
MENU_ITEMS: List[MenuItem] = [
    # ── BREAKFAST ──────────────────────────────────────────────────────────
    MenuItem(id="b1", name="Poha Bowl", category="Breakfast",
        tags=["vegetarian","light","plant-forward","budget-friendly"],
        label="Plant Forward", price=79,
        description="Flattened rice with mustard seeds, turmeric, onion and fresh coriander.",
        short_desc="Poha · Vegetables · Herbs",
        ingredients=["Flattened rice (poha)","Onion","Green chilli","Mustard seeds","Turmeric","Curry leaves","Fresh coriander","Lemon","Salt"],
        profile=["🌱 Plant Forward","🌾 Grain-based","🥕 Contains vegetables"],
        why_on_menu="A familiar, affordable breakfast staple. Light, easy to digest and made with minimally processed ingredients.",
        allergens="Contains mustard. Please check with café staff for cross-contact details.",
        image="https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=130, protein=2.8, fat=2.5, carbs=25.0)),
    MenuItem(id="b2", name="Moong Chilla", category="Breakfast",
        tags=["vegetarian","protein","plant-forward","filling"],
        label="Nourish", price=99,
        description="Savoury lentil pancakes made from soaked moong dal, served with mint chutney.",
        short_desc="Moong dal · Herbs · Mint chutney",
        ingredients=["Yellow moong dal","Ginger","Green chilli","Cumin","Coriander","Salt","Mint chutney"],
        profile=["🌱 Plant Forward","💪 Pulse-based protein","🥬 Contains legumes"],
        why_on_menu="Pulses like moong dal are highlighted in ICMR-NIN dietary guidelines as an important protein source for vegetarian diets.",
        allergens="Please check with café staff regarding cross-contact and specific ingredients.",
        image="https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=155, protein=9.5, fat=2.8, carbs=24.0)),
    MenuItem(id="b3", name="Curd & Fruit Bowl", category="Breakfast",
        tags=["vegetarian","fresh","light","less-sweet"],
        label="Fresh", price=119,
        description="Plain curd with seasonal fruit, a drizzle of honey and a sprinkle of seeds.",
        short_desc="Curd · Seasonal fruit · Seeds",
        ingredients=["Plain curd (dahi)","Seasonal fruit","Flaxseeds","Chia seeds","Honey (optional)"],
        profile=["🍓 Contains fruit","🥛 Dairy-based","🌱 Plant Forward"],
        why_on_menu="Curd and fruit together provide variety across food groups — aligned with ICMR-NIN guidance on diverse daily food intake.",
        allergens="Contains dairy. Seeds may be present. Please check with café staff.",
        image="https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=110, protein=4.5, fat=2.2, carbs=18.0)),
    MenuItem(id="b4", name="Banana Peanut Toast", category="Breakfast",
        tags=["vegetarian","filling","budget-friendly"],
        label="Nourish", price=89,
        description="Wholegrain toast with natural peanut butter, sliced banana and a pinch of cinnamon.",
        short_desc="Wholegrain bread · Peanut butter · Banana",
        ingredients=["Wholegrain bread","Natural peanut butter","Banana","Cinnamon"],
        profile=["🌾 Grain-based","🍌 Contains fruit","🥜 Contains nuts"],
        why_on_menu="Combines whole grains, natural nut butter and fruit — a practical combination providing variety without added complexity.",
        allergens="Contains gluten, peanuts. Please check with café staff.",
        image="https://images.unsplash.com/photo-1484723091739-30990604718b?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=220, protein=7.0, fat=8.5, carbs=30.0)),
    MenuItem(id="b5", name="Vegetable Upma", category="Breakfast",
        tags=["vegetarian","light","more-vegetables","budget-friendly","plant-forward"],
        label="Plant Forward", price=79,
        description="Semolina cooked with carrots, peas, beans, mustard seeds and curry leaves.",
        short_desc="Semolina · Carrots · Peas · Curry leaves",
        ingredients=["Semolina (suji)","Carrot","Green peas","French beans","Onion","Mustard seeds","Curry leaves","Green chilli","Ghee","Salt"],
        profile=["🌱 Plant Forward","🥕 Contains vegetables","🌾 Grain-based"],
        why_on_menu="Upma with vegetables is a classic light breakfast combining grain and vegetables — affordable and familiar for students.",
        allergens="Contains gluten, ghee (dairy). Please check with café staff.",
        image="https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=145, protein=3.5, fat=3.0, carbs=27.0)),
    MenuItem(id="b6", name="Besan Chilla", category="Breakfast",
        tags=["vegetarian","protein","plant-forward","filling","budget-friendly"],
        label="Nourish", price=89,
        description="Gram flour pancakes with onion, tomato, coriander and green chilli.",
        short_desc="Gram flour · Onion · Tomato · Coriander",
        ingredients=["Gram flour (besan)","Onion","Tomato","Green chilli","Coriander","Turmeric","Ajwain","Salt","Oil"],
        profile=["💪 Pulse-based protein","🌱 Plant Forward","🥕 Contains vegetables"],
        why_on_menu="Gram flour is a good plant protein source. Besan chilla is a practical, affordable high-protein breakfast option for students.",
        allergens="Contains gram flour. Please check with café staff.",
        image="https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=170, protein=8.5, fat=5.5, carbs=22.0)),
    MenuItem(id="b7", name="Oats Porridge", category="Breakfast",
        tags=["vegetarian","filling","less-sweet","light"],
        label="Nourish", price=99,
        description="Rolled oats cooked in milk, topped with sliced banana, crushed nuts and a pinch of cinnamon.",
        short_desc="Rolled oats · Milk · Banana · Nuts",
        ingredients=["Rolled oats","Low-fat milk","Banana","Almonds","Walnuts","Cinnamon","No added sugar"],
        profile=["🌾 Grain-based","💪 Contains protein","🍌 Contains fruit"],
        why_on_menu="Oats are a whole grain option consistent with WHO guidance on minimally processed grains. No added sugar — sweetness from banana only.",
        allergens="Contains dairy, tree nuts, gluten. Please check with café staff.",
        image="https://images.unsplash.com/photo-1517673408072-b10e0a0b6e45?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=160, protein=6.0, fat=4.5, carbs=26.0)),
    MenuItem(id="b8", name="Methi Thepla + Curd", category="Breakfast",
        tags=["vegetarian","light","plant-forward","budget-friendly"],
        label="Plant Forward", price=89,
        description="Fenugreek-spiced whole wheat flatbread served with a small bowl of plain curd.",
        short_desc="Fenugreek flatbread · Whole wheat · Curd",
        ingredients=["Whole wheat flour","Fresh methi (fenugreek) leaves","Curd","Turmeric","Red chilli powder","Ajwain","Salt","Oil"],
        profile=["🌱 Plant Forward","🌾 Grain-based","🥬 Contains greens"],
        why_on_menu="Methi is a green leafy vegetable recommended by ICMR-NIN. Thepla with curd combines grain and dairy in a familiar, light format.",
        allergens="Contains gluten, dairy. Please check with café staff.",
        image="https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=175, protein=5.5, fat=5.0, carbs=28.0)),
    MenuItem(id="b9", name="Sprout Breakfast Bowl", category="Breakfast",
        tags=["vegetarian","fresh","light","plant-forward","more-vegetables","budget-friendly"],
        label="Fresh", price=99,
        description="Mixed sprouts with cucumber, tomato, onion, lemon and chaat masala.",
        short_desc="Mixed sprouts · Cucumber · Tomato · Lemon",
        ingredients=["Moong sprouts","Chana sprouts","Cucumber","Tomato","Onion","Lemon juice","Chaat masala","Fresh coriander"],
        profile=["🌱 Plant Forward","💪 Sprouted protein","🥕 Contains vegetables","🍓 Fresh"],
        why_on_menu="Sprouted legumes increase bioavailability of nutrients. A light, high-protein morning option aligned with FSSAI Eat Right guidance.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=105, protein=7.0, fat=0.8, carbs=18.0)),
    MenuItem(id="b10", name="Egg Bhurji & Toast", category="Breakfast",
        tags=["protein","filling","budget-friendly"],
        label="Nourish", price=119,
        description="Scrambled eggs with onion, tomato, green chilli and spices, served with wholegrain toast.",
        short_desc="Scrambled eggs · Onion · Tomato · Toast",
        ingredients=["Eggs","Onion","Tomato","Green chilli","Turmeric","Coriander","Salt","Oil","Wholegrain bread"],
        profile=["💪 Egg protein","🌾 Grain-based","🥕 Contains vegetables"],
        why_on_menu="Eggs are a complete protein source. Paired with wholegrain toast for a practical, filling breakfast combining protein and grain.",
        allergens="Contains eggs, gluten. Please check with café staff.",
        image="https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=195, protein=12.0, fat=9.5, carbs=16.0)),
    MenuItem(id="b11", name="Sattu Drink + Roti", category="Breakfast",
        tags=["vegetarian","protein","budget-friendly","filling","plant-forward"],
        label="Nourish", price=79,
        description="Roasted gram flour drink with lemon and cumin, served with one whole wheat roti.",
        short_desc="Sattu drink · Whole wheat roti",
        ingredients=["Roasted gram flour (sattu)","Lemon","Cumin","Water","Rock salt","Whole wheat roti"],
        profile=["💪 Pulse-based protein","🌾 Grain-based","🌱 Plant Forward"],
        why_on_menu="Sattu is a traditional high-protein ingredient from Indian food culture. Budget-friendly, filling and widely available.",
        allergens="Contains gram flour, gluten. Please check with café staff.",
        image="https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=185, protein=10.5, fat=2.5, carbs=32.0)),
    MenuItem(id="b12", name="Idli Sambar (3 pcs)", category="Breakfast",
        tags=["vegetarian","light","plant-forward","budget-friendly"],
        label="Plant Forward", price=89,
        description="Steamed rice cakes with vegetable sambar and coconut chutney.",
        short_desc="Steamed idli · Vegetable sambar · Coconut chutney",
        ingredients=["Rice","Urad dal","Toor dal","Seasonal vegetables","Tamarind","Mustard seeds","Coconut","Curry leaves"],
        profile=["🌱 Plant Forward","🌾 Fermented grain","🥕 Contains vegetables"],
        why_on_menu="Idli is a fermented, steamed food — aligned with FSSAI guidance on minimally processed preparations. Sambar adds pulse-based protein.",
        allergens="Contains urad dal. Please check with café staff.",
        image="https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=120, protein=3.8, fat=1.5, carbs=24.0)),

    # ── LUNCH ──────────────────────────────────────────────────────────────
    MenuItem(id="l1", name="Rajma Rice Bowl", category="Lunch",
        tags=["vegetarian","plant-forward","filling","budget-friendly"],
        label="Plant Forward", price=149,
        description="Red kidney beans slow-simmered in a tomato-onion gravy, served with steamed rice and seasonal vegetables.",
        short_desc="Rajma · Rice · Seasonal vegetables",
        ingredients=["Rajma (kidney beans)","Basmati rice","Tomato","Onion","Ginger-garlic","Cumin","Coriander powder","Garam masala","Seasonal vegetables","Fresh coriander"],
        profile=["🌱 Plant Forward","💪 Pulse-based protein","🌾 Grain-based","🥕 Contains vegetables"],
        why_on_menu="A combination of pulses and grains providing complementary plant proteins. Familiar, affordable and filling — designed with students in mind.",
        allergens="Please check with café staff regarding cross-contact and specific ingredients.",
        image="https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=165, protein=7.5, fat=2.8, carbs=30.0)),
    MenuItem(id="l2", name="Paneer Grain Bowl", category="Lunch",
        tags=["vegetarian","protein","filling","more-vegetables"],
        label="Nourish", price=179,
        description="Grilled paneer cubes over a bed of whole grain, roasted vegetables and herb dressing.",
        short_desc="Paneer · Whole grain · Vegetables",
        ingredients=["Paneer","Whole grain (millet/wheat)","Bell pepper","Zucchini","Cherry tomato","Olive oil","Cumin","Lemon dressing","Fresh herbs"],
        profile=["💪 Dairy protein","🌾 Grain-based","🥕 Contains vegetables"],
        why_on_menu="Paneer is a practical protein source for vegetarians. Paired with whole grains and vegetables for variety across food groups.",
        allergens="Contains dairy, gluten. Please check with café staff.",
        image="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=210, protein=13.5, fat=9.0, carbs=20.0)),
    MenuItem(id="l3", name="Chana Masala Plate", category="Lunch",
        tags=["vegetarian","plant-forward","filling","budget-friendly","more-vegetables"],
        label="Plant Forward", price=139,
        description="Spiced chickpeas with a tangy tamarind base, served with two rotis and sliced onion.",
        short_desc="Chickpeas · Roti · Spices",
        ingredients=["Chickpeas (chana)","Tomato","Onion","Tamarind","Cumin","Coriander","Amchur","Garam masala","Whole wheat roti"],
        profile=["🌱 Plant Forward","💪 Pulse-based protein","🌾 Grain-based"],
        why_on_menu="Chickpeas are among the legumes recommended by ICMR-NIN. A budget-friendly lunch option with pulses and whole grain bread.",
        allergens="Contains gluten (roti). Please check with café staff.",
        image="https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=175, protein=8.5, fat=3.5, carbs=30.0)),
    MenuItem(id="l4", name="Dal Tadka & Rice", category="Lunch",
        tags=["vegetarian","plant-forward","filling","budget-friendly","light"],
        label="Plant Forward", price=129,
        description="Yellow toor dal tempered with ghee, cumin and dried red chilli, served with steamed rice.",
        short_desc="Toor dal · Steamed rice · Ghee tadka",
        ingredients=["Toor dal","Tomato","Onion","Turmeric","Cumin seeds","Dried red chilli","Ghee","Steamed rice","Fresh coriander"],
        profile=["🌱 Plant Forward","💪 Pulse-based protein","🌾 Grain-based"],
        why_on_menu="Dal-rice is one of the most nutritionally complete everyday combinations from traditional Indian diets — pulses plus grains.",
        allergens="Contains ghee (dairy). Please check with café staff.",
        image="https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=155, protein=6.5, fat=3.0, carbs=28.0)),
    MenuItem(id="l5", name="Vegetable Khichdi", category="Lunch",
        tags=["vegetarian","plant-forward","light","less-sweet","budget-friendly"],
        label="Plant Forward", price=119,
        description="Soft-cooked rice and moong dal with seasonal vegetables, finished with a cumin-ghee tadka.",
        short_desc="Rice · Moong dal · Seasonal vegetables",
        ingredients=["Rice","Yellow moong dal","Seasonal vegetables","Turmeric","Cumin","Ginger","Ghee","Salt"],
        profile=["🌱 Plant Forward","🥕 Contains vegetables","💪 Pulse-based protein"],
        why_on_menu="A gentle, easy-to-digest dish combining grains and pulses. Particularly suitable when students prefer something light.",
        allergens="Contains ghee (dairy). Please check with café staff.",
        image="https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=140, protein=5.5, fat=2.5, carbs=26.0)),
    MenuItem(id="l6", name="Palak Dal & Roti", category="Lunch",
        tags=["vegetarian","plant-forward","more-vegetables","filling","budget-friendly"],
        label="Plant Forward", price=139,
        description="Spinach and toor dal cooked together with spices, served with two whole wheat rotis.",
        short_desc="Spinach dal · Whole wheat rotis",
        ingredients=["Spinach (palak)","Toor dal","Tomato","Onion","Garlic","Cumin","Garam masala","Ghee","Whole wheat roti"],
        profile=["🌱 Plant Forward","🥬 Contains greens","💪 Pulse-based protein"],
        why_on_menu="Green leafy vegetables like spinach are strongly recommended by ICMR-NIN. Combining with dal adds pulse-based protein.",
        allergens="Contains gluten, ghee (dairy). Please check with café staff.",
        image="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=160, protein=7.5, fat=3.5, carbs=27.0)),
    MenuItem(id="l7", name="Chole Bhature (1 pc)", category="Lunch",
        tags=["vegetarian","plant-forward","filling"],
        label="Plant Forward", price=129,
        description="Spiced white chickpeas in a robust gravy, served with one puffed fried bread.",
        short_desc="White chickpeas · Puffed bread · Spiced gravy",
        ingredients=["White chickpeas (kabuli chana)","Tomato","Onion","Ginger-garlic","Anardana","Garam masala","Maida (bhatura)","Oil"],
        profile=["🌱 Plant Forward","💪 Pulse-based protein"],
        why_on_menu="A popular Indian dish combining pulses and bread. Offered as a single serving to keep it practical within a balanced day's eating.",
        allergens="Contains gluten. Please check with café staff.",
        image="https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=250, protein=9.0, fat=10.5, carbs=33.0)),
    MenuItem(id="l8", name="Mixed Veg Sabzi & Rice", category="Lunch",
        tags=["vegetarian","plant-forward","more-vegetables","budget-friendly","light"],
        label="Plant Forward", price=129,
        description="Seasonal mixed vegetable stir-fry with mustard seeds and steamed rice.",
        short_desc="Seasonal vegetables · Mustard seeds · Rice",
        ingredients=["Seasonal mixed vegetables","Mustard seeds","Turmeric","Green chilli","Curry leaves","Steamed rice","Salt","Oil"],
        profile=["🌱 Plant Forward","🥕 Contains vegetables","🌾 Grain-based"],
        why_on_menu="Seasonal vegetable dishes are recommended by both ICMR-NIN and FSSAI. Changes daily based on availability.",
        allergens="Contains mustard. Please check with café staff.",
        image="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=135, protein=3.0, fat=2.5, carbs=27.0)),
    MenuItem(id="l9", name="Soya Chunk Curry & Rice", category="Lunch",
        tags=["vegetarian","protein","filling","plant-forward"],
        label="Nourish", price=149,
        description="Soya chunks in a tomato-onion gravy with whole spices, served with steamed rice.",
        short_desc="Soya chunks · Tomato gravy · Steamed rice",
        ingredients=["Soya chunks (textured soy protein)","Tomato","Onion","Ginger-garlic","Coriander powder","Garam masala","Basmati rice"],
        profile=["💪 High plant protein","🌱 Plant Forward","🌾 Grain-based"],
        why_on_menu="Soya is among the highest plant protein sources. A practical, affordable way to increase protein intake for vegetarians.",
        allergens="Contains soya. Please check with café staff.",
        image="https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=175, protein=14.0, fat=3.5, carbs=22.0)),
    MenuItem(id="l10", name="Egg Curry & Rice", category="Lunch",
        tags=["protein","filling","budget-friendly"],
        label="Nourish", price=159,
        description="Whole boiled eggs in a spiced onion-tomato gravy, served with steamed rice.",
        short_desc="Boiled eggs · Spiced gravy · Steamed rice",
        ingredients=["Boiled eggs","Tomato","Onion","Ginger-garlic","Turmeric","Red chilli","Garam masala","Basmati rice"],
        profile=["💪 Egg protein","🥕 Contains vegetables","🌾 Grain-based"],
        why_on_menu="Eggs are a complete protein with all essential amino acids. Combined with rice this is one of the most protein-complete budget lunches on the menu.",
        allergens="Contains eggs. Please check with café staff.",
        image="https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=195, protein=11.5, fat=7.5, carbs=22.0)),
    MenuItem(id="l11", name="Stuffed Paratha + Curd", category="Lunch",
        tags=["vegetarian","filling","budget-friendly"],
        label="Nourish", price=139,
        description="Two whole wheat parathas stuffed with spiced potato or cauliflower, served with plain curd.",
        short_desc="Aloo/gobi paratha · Plain curd",
        ingredients=["Whole wheat flour","Potato or cauliflower filling","Cumin","Coriander","Green chilli","Ghee","Plain curd"],
        profile=["🌾 Grain-based","🥕 Contains vegetables","🥛 Dairy-based"],
        why_on_menu="Parathas with curd is one of the most practical and popular student meals. Whole wheat flour and curd together provide grain and dairy variety.",
        allergens="Contains gluten, dairy, ghee. Please check with café staff.",
        image="https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=230, protein=6.5, fat=8.0, carbs=35.0)),
    MenuItem(id="l12", name="Brown Rice Rajma Bowl", category="Lunch",
        tags=["vegetarian","plant-forward","filling","more-vegetables"],
        label="Plant Forward", price=159,
        description="Rajma curry on brown rice with a side of roasted seasonal vegetables.",
        short_desc="Rajma · Brown rice · Roasted vegetables",
        ingredients=["Rajma (kidney beans)","Brown rice","Seasonal roasted vegetables","Tomato","Onion","Cumin","Garam masala"],
        profile=["🌱 Plant Forward","💪 Pulse-based protein","🌾 Whole grain","🥕 Contains vegetables"],
        why_on_menu="Brown rice provides more whole grain content than white rice — consistent with WHO guidance on minimally processed grain choices.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=170, protein=8.0, fat=2.5, carbs=32.0)),
    MenuItem(id="l13", name="Tofu Stir-Fry & Millet", category="Lunch",
        tags=["vegetarian","protein","plant-forward","more-vegetables"],
        label="Nourish", price=169,
        description="Pan-tossed tofu with colourful vegetables on a bed of barnyard millet.",
        short_desc="Tofu · Mixed vegetables · Barnyard millet",
        ingredients=["Firm tofu","Bell pepper","Broccoli","Carrot","Barnyard millet (samak)","Soy sauce (minimal)","Ginger","Garlic","Sesame oil"],
        profile=["💪 High plant protein","🌱 Plant Forward","🥕 Contains vegetables"],
        why_on_menu="Tofu is one of the highest plant protein sources. Millet is a whole grain with Indian heritage — both align with ICMR-NIN whole-food guidance.",
        allergens="Contains soya, sesame. Please check with café staff.",
        image="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=180, protein=12.5, fat=6.5, carbs=20.0)),
    MenuItem(id="l14", name="Baingan Bharta & Roti", category="Lunch",
        tags=["vegetarian","plant-forward","more-vegetables","budget-friendly"],
        label="Plant Forward", price=139,
        description="Smoky roasted aubergine with onion, tomato and spices, served with two whole wheat rotis.",
        short_desc="Roasted aubergine · Onion · Whole wheat rotis",
        ingredients=["Aubergine (baingan)","Onion","Tomato","Garlic","Green chilli","Cumin","Garam masala","Mustard oil","Whole wheat roti"],
        profile=["🌱 Plant Forward","🥕 Contains vegetables","🌾 Grain-based"],
        why_on_menu="A traditional smoky dish with vegetables as the centrepiece. Budget-friendly and rich in variety without needing any processed ingredients.",
        allergens="Contains mustard oil, gluten. Please check with café staff.",
        image="https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=145, protein=4.0, fat=4.5, carbs=24.0)),
    MenuItem(id="l15", name="Masoor Dal & Rice", category="Lunch",
        tags=["vegetarian","plant-forward","light","budget-friendly"],
        label="Plant Forward", price=129,
        description="Red lentil dal with a cumin-garlic tadka, served with steamed rice and a small salad.",
        short_desc="Red lentil dal · Steamed rice · Salad",
        ingredients=["Masoor dal (red lentils)","Tomato","Onion","Garlic","Cumin","Turmeric","Basmati rice","Cucumber salad"],
        profile=["🌱 Plant Forward","💪 Pulse-based protein","🌾 Grain-based"],
        why_on_menu="Masoor dal is one of the fastest-cooking pulses — practical and affordable. Lentils feature prominently in ICMR-NIN dietary recommendations.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=148, protein=7.0, fat=1.8, carbs=28.0)),

    # ── SNACKS ─────────────────────────────────────────────────────────────
    MenuItem(id="s1", name="Sprout Chaat", category="Snacks",
        tags=["vegetarian","plant-forward","light","fresh","budget-friendly"],
        label="Fresh", price=79,
        description="Mixed sprouted legumes with diced tomato, cucumber, lemon and chaat masala.",
        short_desc="Sprouted legumes · Vegetables · Chaat masala",
        ingredients=["Mixed sprouts (moong, chana)","Tomato","Cucumber","Onion","Lemon juice","Chaat masala","Fresh coriander"],
        profile=["🌱 Plant Forward","🥕 Contains vegetables","💪 Sprouted protein"],
        why_on_menu="Sprouts are a simple, affordable way to include legumes. Aligned with FSSAI Eat Right India guidance on increasing pulse consumption.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=95, protein=6.5, fat=0.7, carbs=16.0)),
    MenuItem(id="s2", name="Roasted Makhana", category="Snacks",
        tags=["vegetarian","light","less-sweet","plant-forward","budget-friendly"],
        label="Plant Forward", price=59,
        description="Fox nuts lightly roasted with rock salt, pepper and a touch of ghee.",
        short_desc="Fox nuts · Rock salt · Pepper",
        ingredients=["Fox nuts (makhana)","Ghee","Rock salt","Black pepper","Cumin powder"],
        profile=["🌱 Plant Forward","🌾 Minimally processed"],
        why_on_menu="Makhana is a minimally processed snack option — in line with WHO guidance on choosing less processed foods where possible.",
        allergens="Contains ghee (dairy). Please check with café staff.",
        image="https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=350, protein=9.5, fat=0.5, carbs=76.0)),
    MenuItem(id="s3", name="Banana & Nut Butter", category="Snacks",
        tags=["vegetarian","filling","budget-friendly","plant-forward"],
        label="Nourish", price=69,
        description="A whole banana served with a small pot of natural peanut butter for dipping.",
        short_desc="Banana · Natural peanut butter",
        ingredients=["Banana","Natural peanut butter"],
        profile=["🍌 Contains fruit","🥜 Contains nuts"],
        why_on_menu="Fruit and nut combinations are highlighted in ICMR-NIN guidelines as a practical everyday snack option.",
        allergens="Contains peanuts. Please check with café staff.",
        image="https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=195, protein=5.5, fat=8.5, carbs=27.0)),
    MenuItem(id="s4", name="Seasonal Fruit Plate", category="Snacks",
        tags=["vegetarian","fresh","light","less-sweet","plant-forward","budget-friendly"],
        label="Fresh", price=89,
        description="A plate of mixed seasonal fruits — whatever is fresh and available today.",
        short_desc="Mixed seasonal fruit",
        ingredients=["Seasonal fruit (changes daily)","Lemon (optional)","Chaat masala (optional)"],
        profile=["🍓 Contains fruit","🌱 Plant Forward","🌿 Minimally processed"],
        why_on_menu="Daily fruit intake is recommended across WHO, ICMR-NIN and FSSAI guidance. Seasonal availability keeps it affordable and fresh.",
        allergens="Please check with café staff for today's specific fruits and any cross-contact risks.",
        image="https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=65, protein=0.8, fat=0.3, carbs=16.0)),
    MenuItem(id="s5", name="Dhokla (4 pcs)", category="Snacks",
        tags=["vegetarian","light","plant-forward","budget-friendly"],
        label="Plant Forward", price=79,
        description="Steamed fermented gram flour squares with a mustard and sesame tempering.",
        short_desc="Steamed gram flour · Mustard tempering",
        ingredients=["Gram flour (besan)","Semolina","Curd","Ginger","Green chilli","Mustard seeds","Sesame seeds","Curry leaves","Sugar (minimal)"],
        profile=["🌱 Plant Forward","🌾 Fermented","💪 Pulse-based protein"],
        why_on_menu="Dhokla is a steamed, fermented snack — a minimally processed preparation aligned with FSSAI Eat Right India principles.",
        allergens="Contains gram flour, gluten, sesame, dairy. Please check with café staff.",
        image="https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=145, protein=5.5, fat=3.0, carbs=24.0)),
    MenuItem(id="s6", name="Roasted Chana", category="Snacks",
        tags=["vegetarian","protein","light","less-sweet","budget-friendly","plant-forward"],
        label="Plant Forward", price=49,
        description="Dry-roasted black or white chickpeas with rock salt and chilli.",
        short_desc="Roasted chickpeas · Rock salt · Chilli",
        ingredients=["Roasted chickpeas (chana)","Rock salt","Red chilli powder","Chaat masala"],
        profile=["💪 High plant protein","🌱 Plant Forward","🌿 Minimally processed"],
        why_on_menu="Roasted chana is one of the most protein-dense, budget-friendly snacks available. High protein, very low fat, no added sugar.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=364, protein=19.0, fat=6.0, carbs=61.0)),
    MenuItem(id="s7", name="Veg Crudités + Hummus", category="Snacks",
        tags=["vegetarian","fresh","light","less-sweet","more-vegetables","plant-forward"],
        label="Fresh", price=99,
        description="Fresh cucumber, carrot and celery sticks with homemade chickpea hummus.",
        short_desc="Cucumber · Carrot · Celery · Hummus",
        ingredients=["Cucumber","Carrot","Celery","Chickpeas","Tahini","Lemon","Garlic","Olive oil","Cumin"],
        profile=["🌱 Plant Forward","🥕 Contains vegetables","💪 Pulse-based protein","🍓 Fresh"],
        why_on_menu="Vegetables with a legume dip covers two major food groups in one snack — aligned with ICMR-NIN and WHO guidance.",
        allergens="Contains sesame (tahini). Please check with café staff.",
        image="https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=110, protein=4.5, fat=4.5, carbs=14.0)),
    MenuItem(id="s8", name="Mixed Nuts & Seeds", category="Snacks",
        tags=["vegetarian","protein","less-sweet","filling","plant-forward"],
        label="Nourish", price=99,
        description="A measured portion of almonds, walnuts, pumpkin seeds and sunflower seeds.",
        short_desc="Almonds · Walnuts · Pumpkin seeds · Sunflower seeds",
        ingredients=["Almonds","Walnuts","Pumpkin seeds","Sunflower seeds"],
        profile=["🥜 Contains nuts","💪 Contains protein","🌿 Minimally processed"],
        why_on_menu="Nuts and seeds are explicitly recommended by ICMR-NIN as part of the daily diet. Served as a measured portion to keep it practical.",
        allergens="Contains tree nuts. Please check with café staff.",
        image="https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=580, protein=18.0, fat=50.0, carbs=18.0)),
    MenuItem(id="s9", name="Corn Chaat", category="Snacks",
        tags=["vegetarian","light","budget-friendly","plant-forward","fresh"],
        label="Fresh", price=79,
        description="Steamed corn with lime juice, butter, chilli powder and fresh coriander.",
        short_desc="Steamed corn · Lime · Chilli · Coriander",
        ingredients=["Sweet corn","Butter","Lime juice","Red chilli powder","Chaat masala","Fresh coriander"],
        profile=["🌱 Plant Forward","🌾 Grain-based","🍓 Fresh"],
        why_on_menu="Corn is a whole grain option. This simple preparation uses minimal added ingredients — keeping it close to the whole food.",
        allergens="Contains dairy (butter). Please check with café staff.",
        image="https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=110, protein=3.2, fat=2.5, carbs=21.0)),
    MenuItem(id="s10", name="Whole Wheat Crackers + Curd Dip", category="Snacks",
        tags=["vegetarian","light","less-sweet"],
        label="Nourish", price=89,
        description="Baked whole wheat crackers served with a herb-spiced curd dip.",
        short_desc="Whole wheat crackers · Herb curd dip",
        ingredients=["Whole wheat flour","Ajwain","Salt","Oil","Plain curd","Mint","Coriander","Cumin"],
        profile=["🌾 Grain-based","🥛 Dairy-based","🌿 Baked, not fried"],
        why_on_menu="A baked whole grain snack with a dairy dip. Practical, light and pairs grain with dairy — aligned with ICMR-NIN daily food variety guidance.",
        allergens="Contains gluten, dairy. Please check with café staff.",
        image="https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=160, protein=5.0, fat=5.5, carbs=24.0)),
    MenuItem(id="s11", name="Boiled Eggs (2 pcs)", category="Snacks",
        tags=["protein","light","less-sweet","budget-friendly"],
        label="Nourish", price=59,
        description="Two plain boiled eggs with rock salt, black pepper and lemon wedge.",
        short_desc="Boiled eggs · Rock salt · Pepper",
        ingredients=["Eggs","Rock salt","Black pepper","Lemon"],
        profile=["💪 Complete egg protein","🌿 Minimally processed"],
        why_on_menu="Boiled eggs are one of the most protein-complete, minimally processed snack options at the lowest cost. No added ingredients.",
        allergens="Contains eggs. Please check with café staff.",
        image="https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=155, protein=13.0, fat=10.5, carbs=1.1)),
    MenuItem(id="s12", name="Peanut Chikki", category="Snacks",
        tags=["vegetarian","budget-friendly","plant-forward"],
        label="Plant Forward", price=29,
        description="Traditional jaggery and peanut brittle, one piece.",
        short_desc="Jaggery · Peanuts",
        ingredients=["Peanuts","Jaggery"],
        profile=["🥜 Contains nuts","🌱 Plant Forward","🌿 Minimally processed"],
        why_on_menu="Jaggery is an unrefined sweetener used in traditional Indian food culture. Offered as a single small portion — a practical sweet option.",
        allergens="Contains peanuts. Please check with café staff.",
        image="https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=430, protein=10.5, fat=20.0, carbs=55.0)),

    # ── DRINKS ─────────────────────────────────────────────────────────────
    MenuItem(id="d1", name="Unsweetened Masala Tea", category="Drinks",
        tags=["vegetarian","light","less-sweet","budget-friendly"],
        label="Fresh", price=39,
        description="A small cup of chai made with ginger, cardamom and minimal milk — no added sugar.",
        short_desc="Tea · Ginger · Cardamom · No sugar",
        ingredients=["Black tea","Ginger","Cardamom","Cinnamon","Low-fat milk","No added sugar"],
        profile=["☕ Warm beverage","🚫 No added sugar"],
        why_on_menu="Offered without added sugar in line with WHO guidance on limiting free sugars in everyday beverages.",
        allergens="Contains dairy. Please check with café staff.",
        image="https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=25, protein=1.2, fat=0.8, carbs=3.5)),
    MenuItem(id="d2", name="Nimbu Pani", category="Drinks",
        tags=["vegetarian","fresh","light","less-sweet","budget-friendly","plant-forward"],
        label="Fresh", price=39,
        description="Fresh lime water with a pinch of rock salt and cumin powder. Lightly sweetened on request.",
        short_desc="Lime · Rock salt · Cumin",
        ingredients=["Fresh lime juice","Water","Rock salt","Cumin powder","Sugar (optional, minimal)"],
        profile=["🍋 Contains citrus","🚫 Minimal added sugar","🌱 Plant Forward"],
        why_on_menu="A simple, hydrating drink with minimal ingredients. Sugar is optional and minimised — consistent with WHO free-sugar guidelines.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=20, protein=0.2, fat=0.0, carbs=5.5)),
    MenuItem(id="d3", name="Lassi (Plain)", category="Drinks",
        tags=["vegetarian","filling","less-sweet","protein"],
        label="Nourish", price=59,
        description="Chilled churned curd with a pinch of rock salt. Available plain or lightly sweetened.",
        short_desc="Curd · Rock salt · Optional sugar",
        ingredients=["Plain curd (dahi)","Cold water","Rock salt","Sugar (optional, minimal)","Cumin powder (optional)"],
        profile=["🥛 Dairy-based","💪 Contains protein","🌿 Minimally processed"],
        why_on_menu="Curd is highlighted as an important daily food group in ICMR-NIN guidelines. Lassi is a practical, familiar way to include it.",
        allergens="Contains dairy. Please check with café staff.",
        image="https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=65, protein=3.5, fat=1.5, carbs=9.0)),
    MenuItem(id="d4", name="Cold Brew Coffee", category="Drinks",
        tags=["vegetarian","light","less-sweet","budget-friendly"],
        label="Fresh", price=79,
        description="Slow-steeped black coffee served over ice. No added sugar, milk available on request.",
        short_desc="Cold brew coffee · No added sugar",
        ingredients=["Cold brew concentrate","Water","Ice","Milk (optional)"],
        profile=["☕ Cold beverage","🚫 No added sugar"],
        why_on_menu="Offered without added sugar. Milk is optional — keeping this a low free-sugar option consistent with WHO guidance.",
        allergens="Dairy-free by default. Contains coffee/caffeine. Please check with café staff.",
        image="https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=5, protein=0.3, fat=0.0, carbs=0.5)),
    MenuItem(id="d5", name="Turmeric Milk", category="Drinks",
        tags=["vegetarian","less-sweet","filling"],
        label="Nourish", price=69,
        description="Warm milk with turmeric, black pepper and a touch of honey. No refined sugar.",
        short_desc="Milk · Turmeric · Honey",
        ingredients=["Full-fat milk","Turmeric","Black pepper","Honey","Cardamom (optional)"],
        profile=["🥛 Dairy-based","🌿 Minimally processed","🚫 No refined sugar"],
        why_on_menu="A warm milk-based drink without refined sugar. Turmeric and pepper are traditional additions with a long history in Indian food culture.",
        allergens="Contains dairy, honey. Please check with café staff.",
        image="https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=80, protein=3.8, fat=3.5, carbs=9.5)),
    MenuItem(id="d6", name="Coconut Water", category="Drinks",
        tags=["vegetarian","fresh","light","less-sweet","plant-forward","budget-friendly"],
        label="Fresh", price=59,
        description="Fresh tender coconut water, plain and naturally sweet.",
        short_desc="Fresh tender coconut water",
        ingredients=["Fresh tender coconut water"],
        profile=["🌱 Plant Forward","🍓 Fresh","🌿 Minimally processed","🚫 No added sugar"],
        why_on_menu="Coconut water is a natural, minimally processed hydration option with no added sugar — consistent with WHO free-sugar guidance.",
        allergens="Contains coconut. Please check with café staff.",
        image="https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=19, protein=0.7, fat=0.2, carbs=3.7)),
    MenuItem(id="d7", name="Aam Panna", category="Drinks",
        tags=["vegetarian","fresh","light","less-sweet","budget-friendly","plant-forward"],
        label="Fresh", price=49,
        description="Raw mango drink with cumin, mint, rock salt and minimal sugar.",
        short_desc="Raw mango · Cumin · Mint · Rock salt",
        ingredients=["Raw mango","Cumin powder","Mint leaves","Rock salt","Sugar (minimal)","Black salt"],
        profile=["🌱 Plant Forward","🍓 Fresh","🚫 Minimal sugar"],
        why_on_menu="A traditional Indian summer drink using raw mango — a seasonal, locally available fruit. Minimal processing and minimal sugar.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=30, protein=0.3, fat=0.1, carbs=7.5)),
    MenuItem(id="d8", name="Jaljeera", category="Drinks",
        tags=["vegetarian","fresh","light","less-sweet","budget-friendly","plant-forward"],
        label="Fresh", price=39,
        description="Cumin-spiced lemon water with mint and black salt — no added sugar.",
        short_desc="Cumin · Lemon · Mint · Black salt",
        ingredients=["Cumin powder","Lemon juice","Mint leaves","Black salt","Chaat masala","Water"],
        profile=["🌱 Plant Forward","🚫 No added sugar","🍓 Fresh"],
        why_on_menu="A zero-sugar spiced drink from traditional Indian food culture. Entirely natural ingredients, no processing.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=15, protein=0.3, fat=0.1, carbs=3.5)),
    MenuItem(id="d9", name="Sattu Sharbat", category="Drinks",
        tags=["vegetarian","protein","light","less-sweet","budget-friendly","plant-forward"],
        label="Nourish", price=49,
        description="Roasted gram flour with lemon, cumin and water — no sugar.",
        short_desc="Sattu · Lemon · Cumin · No sugar",
        ingredients=["Roasted gram flour (sattu)","Lemon juice","Cumin","Black salt","Water"],
        profile=["💪 Pulse-based protein","🌱 Plant Forward","🚫 No added sugar"],
        why_on_menu="Sattu sharbat is a traditional protein-rich cold drink. No refined sugar, high protein — a genuinely useful option for students.",
        allergens="Contains gram flour. Please check with café staff.",
        image="https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=55, protein=4.5, fat=0.8, carbs=8.5)),
    MenuItem(id="d10", name="Buttermilk (Chaas)", category="Drinks",
        tags=["vegetarian","light","less-sweet","budget-friendly"],
        label="Fresh", price=39,
        description="Thin churned curd with cumin, curry leaves, ginger and a pinch of salt.",
        short_desc="Curd · Cumin · Curry leaves · Ginger",
        ingredients=["Plain curd (dahi)","Water","Cumin powder","Curry leaves","Ginger","Salt"],
        profile=["🥛 Dairy-based","🌿 Minimally processed","🍓 Fresh"],
        why_on_menu="Chaas is one of the most affordable dairy drinks. Curd is a recommended daily food group per ICMR-NIN. No added sugar.",
        allergens="Contains dairy. Please check with café staff.",
        image="https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=35, protein=1.8, fat=0.8, carbs=4.5)),
    MenuItem(id="d11", name="Ginger Lemon Tea", category="Drinks",
        tags=["vegetarian","light","less-sweet","budget-friendly"],
        label="Fresh", price=39,
        description="Black tea with fresh ginger slices and a squeeze of lemon — no added sugar.",
        short_desc="Black tea · Fresh ginger · Lemon · No sugar",
        ingredients=["Black tea","Fresh ginger","Lemon juice","No added sugar"],
        profile=["☕ Warm beverage","🚫 No added sugar","🌱 Plant Forward"],
        why_on_menu="A dairy-free, zero-sugar tea option. Offered for students who prefer a lighter, simpler drink without milk or sweetener.",
        allergens="Dairy-free. Please check with café staff.",
        image="https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=8, protein=0.1, fat=0.0, carbs=2.0)),
    MenuItem(id="d12", name="Mango Lassi (seasonal)", category="Drinks",
        tags=["vegetarian","filling","fresh"],
        label="Fresh", price=79,
        description="Curd blended with fresh mango pulp and a touch of cardamom — minimal sugar.",
        short_desc="Curd · Fresh mango · Cardamom",
        ingredients=["Plain curd (dahi)","Fresh mango pulp","Cardamom","Sugar (minimal)","Ice"],
        profile=["🥛 Dairy-based","🍓 Contains fruit","💪 Contains protein"],
        why_on_menu="Seasonal mango lassi combines curd (a key food group) with fresh fruit. Available only when fresh mango is in season — keeping it local.",
        allergens="Contains dairy. Please check with café staff.",
        image="https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=95, protein=4.0, fat=2.0, carbs=16.0)),
    MenuItem(id="d13", name="Hibiscus Cooler", category="Drinks",
        tags=["vegetarian","fresh","light","less-sweet","plant-forward"],
        label="Fresh", price=59,
        description="Dried hibiscus steeped in cold water with mint, lemon and no added sugar.",
        short_desc="Hibiscus · Mint · Lemon · No sugar",
        ingredients=["Dried hibiscus flowers","Mint leaves","Lemon juice","Cold water","No added sugar"],
        profile=["🌱 Plant Forward","🚫 No added sugar","🍓 Fresh"],
        why_on_menu="A zero-sugar floral drink. Naturally vibrant colour from hibiscus — no artificial colouring. Consistent with WHO free-sugar guidance.",
        allergens="Please check with café staff regarding cross-contact.",
        image="https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&auto=format&fit=crop",
        nutrition=Nutrition(calories=12, protein=0.1, fat=0.0, carbs=3.0)),
]
